name: linter-check

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: npm install
        run: npm install
      - name: Run linter
        run: make lint
